### ISSUE TITLE
Error while attache user to role

### ISSUE THREAD

**Issue by devmsh** [lizhineng/nova-permission-tool#2]
SQLSTATE[42703]: Undefined column: 7 ERROR: column "id" does not exist LINE 1: ..."model_id", "model_type") values ($1, $2, $3) returning "id" ^ (SQL: insert into "model_has_roles" ("role_id", "model_id", "model_type") values (1, 1, App\User) returning "id")

**Comment by lizhineng** [comment]
I cannot reproduce that, sorry for the inconvenience. Are you using UUID for your user model? Or, could you tell me your `model_has_roles` table structure?

**Comment by lizhineng** [comment]
I cannot reproduce that, sorry for the inconvenience. Could you tell me more detail?

**Comment by devmsh** [comment]
All what I do is installing fresh Laravel, Nova, and Install this package.

The weak entities did not include "id" fields, and this error appears once I try to attach role to user.

I tried it on MySQL and PostgreSQL and both return the same problems

**Comment by lizhineng** [comment]
Thanks your information, I tried it twice and still cannot reproduce the issue, here is my steps:
1. Install whole new Laravel by `laravel new laravel-test` and `cd laravel-test`, edit `.env` file to update the database settings
2. Install [Nova](https://nova.laravel.com/releases)
* Download release and extract it to your app root directory, and named 'nova'
* Edit composer.json and `composer update` again
* Exec `php artisan nova:install` and `php artisan migrate`
3. Install [Spatie's Permission Package](https://github.com/spatie/laravel-permission)
* `composer require spatie/laravel-permission`
* `php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"`
* `php artisan migrate`
4. Install [Permission Tool](https://github.com/lizhineng/nova-permission-tool)
* `composer require lizhineng/nova-permission-tool`
* Add `new \Lizhineng\PermissionTool\PermissionTool,` to the fields methods in NovaServiceProvider
* `php artisan vendor:publish --provider="Lizhineng\PermissionTool\ToolServiceProvider"`
5. Create a new user to log in Nova

Hope this will help you :-) Waiting your feedback.

**Comment by bsobbe** [comment]
Still no solution??

UPDATE: 
The problem for me has been solved by adding auto increment `id` to the table that I was trying to add record. seems like `postgreSQL` or `laravel` do not let you to insert to the table that does not have auto increment `id`
